### ISSUE TITLE
AstralKeys MinimapButton.lua throws an error in LuckyOne UI

### ISSUE THREAD

**Issue by nzall** [astralguild/AstralKeys#32]
I'm using AstralKeys and LuckyOneUI (https://www.curseforge.com/wow/addons/elvui_luckyoneui), which is a modification for ElvUI that among other things has a special grid layout for minimap buttons below the minimap. However, when using AstralKeys, the minimap button does not appear and I'm getting the below error caught by Buggrabber:

1x AstralKeys\MinimapButton.lua:29: attempt to index field 'general' (a nil value)
[string "@AstralKeys\MinimapButton.lua"]:29: in function <AstralKeys\MinimapButton.lua:25>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...vUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...vUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by carlwoodhouse** [comment]
same thing with elvui

**Comment by sinfonianartist** [comment]
Which version of ElvUI are you using? I have the latest version installed and I'm unable to repro this issue. I have AstralKeys and LuckyOneUI enabled and the minimap button seems to show up correctly.

![image](https://user-images.githubusercontent.com/1711676/165830592-cffc6c2c-6c98-4eaf-9281-fae9c509169c.png)

**Comment by nzall** [comment]
> Which version of ElvUI are you using?

I am not sure, and my sub expired yesterday, so I'm unable to answer this. However, I did update my UI every day with wowup, so it was on multiple versions, including most likely the most recent one.

that being said, my minimap buttons were NOT on my minimap, but rather on a grid below it. I don't know which addon it was, it might have been ProjectAzilroka.

That being said, I did use almost 200 addons, so I don't think I can say for sure which addon caused it.

**Comment by sinfonianartist** [comment]
So that line of code essentially tells the addon when it's initializing that the AceDB library, one of the included libraries for WoW, to hide the button on the minimap based on settings you have.

So if there's some addon that's causing the manipulation of this field that's probably what's causing it. It has to be something that's playing with the minimap specifically. 

This may also be a weird combination of issues and having 200 addons can be problematic as all of these things can be modified by each other, they aren't sandboxed unfortunately.

**Comment by carlwoodhouse** [comment]
this actually only happened once for me with elv and on one char only .. went away after that!
